name: Daily version fetch

on:
  workflow_call:

permissions:
  contents: write

jobs:
  fetch-version:
    name: Look for new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: 'version-list'

      - name: Set up commit bot info
        run: |
          git config user.name "Daily Fetch Bot"
          git config user.email "actions@github.com"

      - name: Run fetch.sh, update branch
        run: |
          ./fetch.sh
          git commit -am "new version: $upstream" || true
          git push
